version: '2'
services:
  iot-gateway-schedulejob:
    scale: 1
    start_on_create: true
  mw-informationpublish-chinashine:
    scale: 1
    start_on_create: true
  iot-gateway-zuul:
    scale: 1
    start_on_create: true
  iot-gateway-base:
    scale: 1
    start_on_create: true
  iot-gateway-syslog:
    scale: 1
    start_on_create: true
  mw-carpark-jiehun:
    scale: 1
    start_on_create: true
  mw-light-kuaisicong:
    scale: 1
    start_on_create: true
  mw-wifi-huawei:
    scale: 1
    start_on_create: true
  mw-airconditioning-hailin:
    scale: 1
    start_on_create: true
  mw-visualintercom-taichuan:
    scale: 1
    start_on_create: true
  mw-video-haikang:
    scale: 1
    start_on_create: true
  iot-gateway-eureka:
    scale: 1
    start_on_create: true
  lbs-gateway-zuul:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: iot-gateway-zuul
        source_port: 80
        target_port: 8010
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  iot-gateway-alarmlinkage:
    scale: 1
    start_on_create: true
