# "docker-compose.yml"
#前台运行打印日志：docker-compose up #前台运行一次
#后台运行命令： docker-compose up -d   #如果只运行一次，就docker run; docker run
#查看运行情况： docker-compose ps
#停止运行：    docker-compose kill
#查看日志：    docker-compose logs -f
#查看日志：    docker-compose logs -f --tail 50 iot-platform   查看iot-platform最后的50条
#查看日志：    docker-compose down #删除上次所有运行记录&停止，否则 docker-compose up,还是接着上次的运行记录 （这样下次使用docker-compose up时就一定会是新容器了）；
#重新启动单个容器：docker-compose restart nginx
#proxy_pass  http://[宿主机IP]:8000; 多个容器访问，ip问题。

#如何在Nginx配置中使用OS环境变量？ https://cloud.tencent.com/developer/ask/150892/answer/262145
#论Docker容器中的Nginx配置文件如何读取系统/容器的环境变量 https://blog.csdn.net/jiangqian6481/article/details/78310247
#Dockerfile与docker-compose设置环境变量 https://blog.csdn.net/ywk_hax/article/details/86531348
# docker-compose.yml 官方编辑文档地址： https://docs.docker.com/compose/compose-file/

### http://10.104.16.46/   rancher访问地址
### http://iot.ourslook.com:8080/adminserver
### https://iot.ourslook.com/iot-license
### https://iot.ourslook.com/eureka/
### https://iot.ourslook.com/iot-platform-base/swagger-ui.html

version: '3.7'
services:
  iot-adminserver:
    image: hub.c.163.com/dazer1992/adminserver:latest
    container_name: adminserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      front:

  iot-zuul:
    image: hub.c.163.com/dazer1992/iot-zuul:latest
    container_name: iot-zuul
    restart: unless-stopped
    ports:
      - "8010:8010"
    networks:
      front:

  iot-eureka:
    image: hub.c.163.com/dazer1992/iot-eureka
    container_name: eureka
    restart: unless-stopped
    depends_on:
      - iot-adminserver
    ports:
      - "8001:8000"

  iot-license:
    image: hub.c.163.com/dazer1992/iot-license:latest
    container_name: iot-license
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    ports:
      - "8988:8988"
    networks:
      - front
      - backend

  iot-platform:
    image: hub.c.163.com/dazer1992/iot-platform-base:0.01
    container_name: iot-platform-base
    volumes: #磁盘映射；解决容器内和容器外时间不一致的问题
      - "/usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    ports:
      - "8002:8881"
    networks:
      - front
      - backend

  iot-platform-alarmlinkage:
    image: hub.c.163.com/dazer1992/iot-platform-alarmlinkage
    container_name: iot-platform-alarmlinkage
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    ports:
      - "8888:8888"

networks:
  front:

  backend:
