version: '2'
services:
  node-exporter:
    image: prom/node-exporter:latest
    stdin_open: true
    tty: true
  grafana:
    image: grafana/grafana:5.0.0
    stdin_open: true
    tty: true
    links:
    - prometheus:prometheus
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    ports:
    - 3000:3000/tcp
  cadvisor:
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
  prometheus-rancher-exporter:
    image: infinityworks/prometheus-rancher-exporter:latest
    environment:
      CATTLE_URL: http://192.168.0.208/v2-beta
      CATTLE_ACCESS_KEY: E293DAE1434DFA8B94BD
      CATTLE_SECRET_KEY: pzuef9SHgZDyDw2ijtyMkHCr2UaCrnPeq4oGR4it
      HIDE_SYS: 'YES'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: '''true'''
  prometheus:
    image: prom/prometheus
    stdin_open: true
    volumes:
    - /usr/local/docker_volume/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - /usr/local/docker_volume/prometheus/data:/prometheus
    tty: true
    links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    ports:
    - 9090:9090/tcp
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
