version: '2'
services:
  docker-registry-ui:
    image: joxit/docker-registry-ui
    environment:
      REGISTRY_TITLE: iot honghu registry
      REGISTRY_URL: http://iotrancher.bgysmartcity.com:5000
      URL: http://iotrancher.bgysmartcity.com:8082
    stdin_open: true
    tty: true
    ports:
    - 8082:80/tcp
    labels:
      io.rancher.container.pull_image: always
  registry:
    image: registry:latest
    stdin_open: true
    volumes:
    - /usr/local2/docker_volume/registry/config/config.yml:/etc/docker/registry/config.yml
    - /usr/local2/docker_volume/registry/registry:/var/lib/registry
    tty: true
    ports:
    - 5000:5000/tcp
    labels:
      io.rancher.container.start_once: 'true'
