# "docker-compose.yml"
#前台运行打印日志：docker-compose up #前台运行一次
#后台运行命令： docker-compose up -d   #如果只运行一次，就docker run; docker run
#查看运行情况： docker-compose ps
#停止运行：    docker-compose kill
#查看日志：    docker-compose logs -f
#查看日志：    docker-compose down #删除上次所有运行记录&停止，否则 docker-compose up,还是接着上次的运行记录 （这样下次使用docker-compose up时就一定会是新容器了）；


# docker-compose 命令详解 https://www.cnblogs.com/linpd/p/11008885.html
# 参考链接地址 https://github.com/kkmike999/docker-compose-php-nginx-mysql
# 这个参考链接有启动mysql的； 还有依赖关系，依赖的就是先启动。

# 进入容器内部&查看容器结构
# 1：docker-compose exec container_name bash
# 2：docker-compose exec nginx  bash
#  nginx默认在nginx.conf引入了conf.d*,因此，我们这里直接覆盖nginx.conf; include /etc/nginx/config.d/*.conf 是多层嵌套的 nginx配置的结构是http>server>location
#
#  ├── conf.d
#  │ ├── default.conf
#  └── nginx.conf

# 访问地址： http://localhost:8000/


version: '3'
services:
  nginx:
    image: nginx:1.14.2 #mini镜像，https://hub.docker.com/_/nginx
    # 端口映射
    ports:
      - "8000:80" #外部端口：内部端口
      - 443:443
    # 数据卷
    volumes: #磁盘映射； 当前目录下面的data/conf.d映射到容器里面
      # - "./data/conf.d:/etc/nginx/conf.d" #不使用这个，我们直接使用 根 nginx.conf
      - "./data/conf:/etc/nginx"
      - "./data/html:/usr/share/nginx/html"







