version: '2'
services:
  iot-gateway-schedulejob:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-schedulejob:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/iot-gateway-schedulejob:/logs/iot/
    tty: true
    ports:
    - 8994:8994/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-zuul:
    image: hub.c.163.com/dazer1992/iot-zuul:latest
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/zuul:/logs/iot/
    tty: true
    ports:
    - 8010:8010/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-base:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-base:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/iot-gateway-base:/logs/iot/
    tty: true
    ports:
    - 8991:8991/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-syslog:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-syslog:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/iot-gateway-syslog:/logs/iot/
    tty: true
    ports:
    - 8993:8993/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-syslog:
    image: hub.c.163.com/dazer1992/iot-platform-syslog:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    tty: true
    ports:
    - 8887:8887/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-license:
    image: hub.c.163.com/dazer1992/iot-license:latest
    stdin_open: true
    tty: true
    ports:
    - 8988:8988/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-base:
    image: hub.c.163.com/dazer1992/iot-platform-base:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-platform-base:/logs/iot/
    tty: true
    ports:
    - 8881:8881/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  mw-light-kuaisicong:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/mw-light-kuaisicong:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/mw-light-kuaisicong:/logs/iot/
    tty: true
    ports:
    - 8901:8901/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-eureka:
    image: hub.c.163.com/dazer1992/iot-eureka
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.pull_image: always
  adminserver:
    image: hub.c.163.com/dazer1992/adminserver:latest
    stdin_open: true
    tty: true
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.pull_image: always
  mw-airconditioning-hailin:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/mw-airconditioning-hailin:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/mw-airconditioning-hailin:/logs/iot/
    tty: true
    ports:
    - 8902:8902/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-alarmlinkage:
    image: hub.c.163.com/dazer1992/iot-platform-alarmlinkage:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    tty: true
    ports:
    - 8888:8888/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-alarmlinkage:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-alarmlinkage:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    volumes:
    - /usr/local/logs/iot-gateway-alarmlinkage:/logs/iot/
    tty: true
    ports:
    - 8992:8992/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-schedulejob:
    image: hub.c.163.com/dazer1992/iot-platform-schedulejob:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    tty: true
    ports:
    - 8889:8889/tcp
    labels:
      io.rancher.container.pull_image: always
