##############
##############
##### rancher 版本
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'exporter-metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:

  - job_name: 'HostsMetrics'
    dns_sd_configs:
      - names:
          - node-exporter
        refresh_interval: 15s
        type: A
        port: 9100

  - job_name: 'DockerContainerMetrics'
    dns_sd_configs:
      - names:
          - cadvisor
        refresh_interval: 15s
        type: A
        port: 8080

  - job_name: 'RancherApi'
    dns_sd_configs:
      - names:
          - 'prometheus-rancher-exporter'
        refresh_interval: 15s
        type: A
        port: 9173

  - job_name: 'Mysql'
    static_configs:
      - targets: #http://39.98.173.142/metrics  9104, 这里我们映射了一下，使用了80端口
          - '39.98.173.142:80'
