version: '2'
services:
  iot-platform-base:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-base:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-platform-base:/logs/iot/
    tty: true
    labels:
      io.rancher.container.pull_image: always
  iot-eureka:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-eureka
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.pull_image: always
  adminserver:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/adminserver:latest
    stdin_open: true
    tty: true
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-base-2:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-base:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-platform-base:/logs/iot/
    tty: true
    labels:
      io.rancher.container.pull_image: always
  iot-zuul:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-zuul:latest
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/zuul:/logs/iot/
    tty: true
    ports:
    - 8010:8010/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-syslog:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-syslog:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    tty: true
    ports:
    - 8887:8887/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-alarmlinkage:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-alarmlinkage:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    network_mode: host
    tty: true
    ports:
    - 8888:8888/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-base-lbs:
    image: rancher/lb-service-haproxy:v0.9.13
    ports:
    - 8881:8881/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: host.name=test
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  iot-platform-schedulejob:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-schedulejob:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    tty: true
    ports:
    - 8889:8889/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-platform-upperapp:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-platform-upperapp:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    tty: true
    ports:
    - 8882:8882/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-license:
    image: iotrancher.bgysmartcity.com:5000/bgytonghu/iot-license:latest
    stdin_open: true
    tty: true
    ports:
    - 8988:8988/tcp
    labels:
      io.rancher.container.pull_image: always
