version: '2'
services:
  iot-eureka:
    image: hub.c.163.com/dazer1992/iot-eureka
    environment:
      spring.profiles.active: gateway
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-eureka:/logs/iot/
    tty: true
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-schedulejob:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-schedulejob:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-gateway-schedulejob:/logs/iot/
    tty: true
    ports:
    - 8889:8889/tcp
    labels:
      io.rancher.container.pull_image: always
  middleware-video-haikang:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/mw-video-haikang:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/mw-video-haikang:/logs/iot/
    tty: true
    ports:
    - 8909:8909/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-zuul:
    image: hub.c.163.com/dazer1992/iot-zuul:latest
    environment:
      spring.profiles.active: gateway
    stdin_open: true
    tty: true
    ports:
    - 80:8010/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-base:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-base:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-gateway-base:/logs/iot/
    tty: true
    ports:
    - 8991:8991/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-syslog:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-syslog:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-gateway-syslog:/logs/iot/
    tty: true
    ports:
    - 8993:8993/tcp
    labels:
      io.rancher.container.pull_image: always
  iot-gateway-alarmlinkage:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/iot-gateway-alarmlinkage:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs/iot-gateway-alarmlinkage:/logs/iot/
    tty: true
    ports:
    - 8992:8992/tcp
    labels:
      io.rancher.container.pull_image: always
  mw-face-wangfeng:
    image: registry.cn-shenzhen.aliyuncs.com/dazer/mw-face-wangfeng:0.01
    environment:
      spring.profiles.active: test
    stdin_open: true
    volumes:
    - /usr/local/logs//mw-face-wangfeng:/logs/iot/
    tty: true
    ports:
    - 8904:8904/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
